# Generated by Django 5.1.1 on 2024-10-06 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PromptRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_prompt', models.TextField()),
                ('new_prompt', models.TextField()),
                ('original_rating', models.IntegerField(blank=True, null=True)),
                ('new_rating', models.IntegerField(blank=True, null=True)),
                ('original_feedback', models.CharField(blank=True, max_length=10, null=True)),
                ('new_feedback', models.CharField(blank=True, max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
